services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: smartfind
      POSTGRES_PASSWORD: smartfind
      POSTGRES_DB: smartfind
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f -L http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  frontend:
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:4173"

volumes:
  pgdata:
