version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartfind-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app  
      - ./backend/requirements.txt:/app/requirements.txt
    env_file:
      - .env
    restart: unless-stopped
