version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smartfind-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app  
      - ./backend/requirements.txt:/app/requirements.txt
      - ./data/sqlite:/app/data
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smartfind-frontend
    ports:
      - "5173:4173" 
    depends_on:
      - backend
    restart: unless-stopped
